### ISSUE TITLE
selecting the same clientside and serverside TCP profile results is failing

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-appsvcs-templates#10]
### Environment
 * FAST RPM Version: 1.1.0
 * BIG-IP Version: 15.1.0.3

### Summary
When selecting the same TCP profile on clientside and serverside, the rendered AS3 is generated correctly, but when pushed in the BIG-IP device, the following error occur:

            "code": 422,
            "message": "declaration failed",
            "response": "01070734:3: Configuration error: Less than the required minimum number of profiles found on /TenantName/AppName/serviceMain: Exactly 1 of (UDP Profile (clientside), TCP Profile (clientside), SCTP Profile (clientside))"

### Steps To Reproduce
Deploy correctly a FAST template like the default one for HTTP ( bigip-fast-templates/http).

I am using the following config:
{
  "virtual_address": "192.168.122.24",
  "enable_pool": true,
  "make_pool": true,
  "pool_members": [
    "10.0.0.1",
    "10.0.0.2",
    "10.0.0.3",
    "10.0.0.201"
  ],
  "load_balancing_mode": "least-connections-member",
  "enable_monitor": true,
  "make_monitor": true,
  "enable_snat": true,
  "snat_automap": true,
  "enable_persistence": false,
  "enable_tls_server": false,
  "enable_tls_client": false,
  "make_tcp_ingress_profile": false,
  "make_tcp_egress_profile": false,
  "make_http_profile": false,
  "enable_acceleration": false,
  "enable_compression": false,
  "enable_multiplex": false,
  "virtual_port": 80,
  "pool_port": 80,
  "slow_ramp_time": 300,
  "tcp_ingress_profile_name": "/Common/tcp-wan-optimized",
  "tcp_egress_profile_name": "/Common/tcp-lan-optimized",
  "http_profile_name": "/Common/http",
  "tenant_name": "TenantName",
  "app_name": "AppName"
}

Change the TCP profile to match the same on client and server (whichever you take fail as far as you keep them the same, from the testing i did).

### Expected Behavior
Expected behavior would be to accept that clientside and serverside TCP profiles can be the same, and push + apply this config.
The issue is an AS3 issue, as i tested it with pure AS3 calls, but it is showing up in FAST, and with no clear explanation of the issue in FAST "GUI". Had to go to restnoded.log to get the details (but that is another problem ;-)).

### Actual Behavior
Response in the GUI is "declaration failed". when you use REST API to get insights on the task.
you have a code 422, with the following content.

{
    "id": "2a0a4b17-04d3-4115-9e90-48c3356ce51e",
    "code": 422,
    "message": "declaration failed",
    "name": "bigip-fast-templates/http",
    "parameters": {
        "virtual_address": "192.168.122.24",
        "enable_pool": true,
        "make_pool": true,
        "pool_members": [
            "10.0.0.1",
            "10.0.0.2",
            "10.0.0.3",
            "10.0.0.201"
        ],
        "enable_snat": true,
        "snat_automap": true,
        "enable_persistence": false,
        "enable_tls_server": false,
        "enable_tls_client": false,
        "make_tcp_ingress_profile": false,
        "make_tcp_egress_profile": false,
        "make_http_profile": false,
        "enable_acceleration": false,
        "enable_compression": false,
        "enable_multiplex": false,
        "virtual_port": 80,
        "tcp_ingress_profile_name": "/Common/tcp-wan-optimized",
        "tcp_egress_profile_name": "/Common/tcp-lan-optimized",
        "http_profile_name": "/Common/http",
        "tenant_name": "TenantName",
        "app_name": "AppName"
    },
    "tenant": "TenantName",
    "application": "AppName"
}

My issues here is that the content provided as the answer, is not the one i sent (i picked tcp-wan-optimized and tcp-wan-optimized). It is the one that was previously existing and that has been kept.

If i undeploy the app, and try directly with the same tcp profile on client and server, i got the following message ini the task list:
{
    "id": "b7cbc9be-b632-461d-bf7f-2002e317d63b",
    "code": 422,
    "message": "declaration failed",
    "name": "",
    "parameters": {},
    "tenant": "TenantName",
    "application": "AppName"
}

**Comment by zinkem5** [comment]
Thanks for the feedback we are looking into this. The FAST RPM will continue to receive improvements to error reporting in future releases. 

> The issue is an AS3 issue, as i tested it with pure AS3 calls, but it is showing up in FAST, and with no clear explanation of the issue in FAST "GUI". Had to go to restnoded.log to get the details (but that is another problem ;-)).

Has this issue been filed with the AS3 team?

**Comment by mstokes-f5** [comment]
This has been fixed with the bigip-fast-templates shipped with FAST v1.5.0. If you are still encountering this issue after upgrading to FAST v1.5.0 (and also updating the bigip-fast-templates template set), please re-open this issue.
