### ISSUE TITLE
RFE request for SAP FAST Template creation

### ISSUE THREAD

**Issue by jjkendrick** [F5Networks/f5-appsvcs-templates#102]
We have a customer who is requesting a FAST template for SAP.  Not sure if this is on the list of templates yet, but please add this request to the list if so.  Thank you.

**Comment by shyawnkarim** [comment]
We currently do not have an SAP template planned in the backlog. Can you provide some details around your use case and some details on what you are looking for?

**Comment by jjkendrick** [comment]
Hi Shyawn,

I have a customer who is wanting to move to the new FAST templates.  They are currently using Sharepoint and SAP iApps.  It is still a use-case for them so I told them I would ask for an RFE for them.


Kind Regards,

[https://cdn.f5.com/webcommon/email-signature/images/f5-logo-rgb-30x30.jpg]<https://f5.com/>
Jenny Kendrick | Solutions Engineer
***@***.******@***.***>
