### ISSUE TITLE
Custom Templates - inline editing

### ISSUE THREAD

**Issue by paolobeta71** [F5Networks/f5-appsvcs-templates#105]
This is a new feature request in order to have the ability to edit FAST templates directly from the BIG-IP GUI.

Working with FAST Custom templates there is sometimes the need to edit and modify something in order to support new functionalities in the App deployment.
The standard way now is to have a local copy of the custom template, edit it, save and zip. Then you can upload the new template to FAST. 

This request is to make possible custom templates can be cloned and edited directly from the FAST GUI so that a new version can be directly modified inline without the need to work offline on it.

Also important could be to be able to export the existing working template from the GUI.

**Comment by DumpySquare** [comment]
Hi @paolobeta71, most of this is supported through the f5 vscode extension.  The vscode-f5 extension is community supported but does provide a robust development workspace for authoring F5 automation workflows.

Take a look here:  https://f5devcentral.github.io/vscode-f5/#/fast

**Comment by paolobeta71** [comment]
Hi Thanks. yes I know this extension and is really helpful but more maybe devops oriented. My idea was more to give also to netops a template management tool from the BIGIP GUI and speed up and simplify this task

**Comment by shyawnkarim** [comment]
@paolobeta71, thanks for submitting this request. We are now tracking it internally with ID MYSTIQUE-648.

**Comment by shyawnkarim** [comment]
Closing.

@paolobeta71, we are working on a different template editing solution and will not be pursing this one at this time. Thanks for your request.
