### ISSUE TITLE
Exchange Template Incorrectly references SNAT Pool

### ISSUE THREAD

**Issue by j-zehnder** [F5Networks/f5-appsvcs-templates#106]
### Environment
 * FAST RPM Version: 1.17.0
 * BIG-IP Version: 15.1.5

### Summary
Exchange template produces invalid declaration when selecting existing SNAT pool

### Steps To Reproduce
List the steps to reproduce the behavior:
* SNAT - checked
* SNAT Automap - unchecked
* FAST-Generated SNAT Pool - Unchecked
* BIG-IP SNAT Pool - select existing pool defined by AS3 `/Common/Shared/default_snat`
    * Note, the BIG-IP SNAT Pool is a dropdown selection and not free-form text.

### Expected Behavior
Template should produce a valid declaration

### Actual Behavior
the following text is visible in Debug view:
```json
"snat": {
    "bigip": {
        "bigip": "/Common/Shared/default_snat"
      }
},
```
nested bigip keys are invalid

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this internally with ID MYSTIQUE-649.
