### ISSUE TITLE
Clarification request on iApp and FAST template compatibility

### ISSUE THREAD

**Issue by GlenWillms** [F5Networks/f5-appsvcs-templates#109]
Can someone explain this statement:

Warning
_We strongly recommend not using both FAST AND iApp templates together as these templating solutions are incompatible with each other. Using both FAST and iApps is likely to create configuration and source-of-truth conflicts, resulting in an undesirable end-state._

Source: https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/getting-started.html#getting-started

Not all iApp templates have been replaced and F5 customers will have a reason to run both concurrently. If there is a reason to be cautious missing iApp and FAST templates it would be go to know to aid F5 customers migration from iApps to FAST.

**Comment by G-gonzalezjimenez** [comment]
Hi Glen, thanks for the conversation. We will follow up internally as discussed and close this issue.
