### ISSUE TITLE
deploy app via api clears params

### ISSUE THREAD

**Issue by DumpySquare** [F5Networks/f5-appsvcs-templates#11]
### Environment
 * FAST RPM Version:1.1.0
 * BIG-IP Version: 14.1.2.3

### Summary
When sending following api call body, app deployment fails.  Rest logs indicate AS3 property match pattern problem but it seems that is because fast is not forwarding the supplied params 

***----- template -----***
```
{
    "class": "ADC",
    "schemaVersion": "3.20.0",
    "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
    "{{tenant_name}}": {
        "class": "Tenant",
        "{{application_name}}": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "10.0.1.10"
                ],
                "pool": "web_pool"
            },
            "web_pool": {
                "class": "Pool",
                "monitors": [
                    "http"
                ],
                "members": [
                    {
                        "servicePort": 80,
                        "serverAddresses": [
                            "192.0.1.10",
                            "192.0.1.11"
                        ]
                    }
                ]
            }
        }
    }
}
```

***----- post body to deploy -----***
```
{
    "name": "test/testTemplate",
    "params": {
        "tenant_name": "qwer",
        "application_name": "asdf"
    }
}
```
***----- error from restnoded -----***
```
Fri, 10 Jul 2020 16:15:37 GMT - warning: [appsvcs] {"status":422,"message":"declaration is invalid","errors":[": propertyName \"\" should match pattern \"^[A-Za-z][0-9A-Za-z_.-]*$\""],"level":"warning"}
```
after attempting to deploy via api, the GUI shows blank inputs to the inputs and rendered views.

### Steps To Reproduce
import new template above
deploy via gui works (this confirms as3 declaration)
deploy via api with supplied body - replies with 422 - bad declaration

### Expected Behavior
api post should deploy application like gui

### Actual Behavior
api app deployment results in a 422 - bad declaration

Not completely sure what is going on here, but it seems that fast is not passing the variables as parameters to the rendered as3 declaration.

- More robust logging of fast would help
- passing back the actual errors from as3 in the api response would also help (currently responds with status and message (422-declaration is invalid".  Like log message from restnoded above

**Comment by zinkem5** [comment]
Thanks for your feedback.


The correct key to use to specify parameters is "parameters"-- this should work:
```
{
    "name": "test/testTemplate",
    "parameters": {
        "tenant_name": "qwer",
        "application_name": "asdf"
    }
}
```
Documentation link here: https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/_static/apidocs.html#operation/createApplication

The error message received is confusing, and the dev team will improve this error, stay tuned.

Please try the recommended edit and let us know if it doesn't work.

Thanks!

**Comment by DumpySquare** [comment]
that got it.  Thank you!
