### ISSUE TITLE
FAST creates telemetry streaming related objects in /Common/Shared

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-appsvcs-templates#116]
### Environment
 * FAST RPM Version: 1.22.0
 * BIG-IP Version: 16.1.3.2

### Summary

FAST creates telemetry streaming related objects in `/Common/Shared`. It does so even when telemetry streaming is not installed.

This seems undocumented and is not desirable in all use-cases.

[Appendix A: API Reference](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/api-ref.html#appendix-a-api-reference) of FAST provides a [FAST settings schema](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/_static/apidocs.html#tag/FAST-Extension/operation/getFastSettingsSchema) which suggests `enable_telemetry` controls log forwarding to telemetry streaming.

Setting `enable_telemetry: false` has no effect on the created configuration objects.

```json
{
  "type": "object",
  "properties": {
    "enable_telemetry": {
      "type": "boolean",
      "title": "Enable Telemetry Streaming log forwarding",
      "description": "Automatically setup log forwarding for Telemetry Streaming when deploying FAST applications.\nMore information can be found [here](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html)\n",
      "propertyOrder": 0,
      "format": "checkbox"
    },
...
  "title": "FAST Settings",
  "description": "",
  "definitions": {},
  "$schema": "http://json-schema.org/schema#"
}
```

Here is a list of objects created by FAST, it may not be complete:

```
ltm pool /Common/Shared/fast_telemetry
ltm rule /Common/Shared/fast_telemetry_local_rule
ltm virtual /Common/Shared/fast_telemetry_local
ltm profile request-log /Common/Shared/fast_telemetry_traffic_log_profile
security log profile /Common/Shared/fast_telemetry_afm_security_log_profile
security log profile /Common/Shared/fast_telemetry_asm_security_log_profile
sys log-config publisher /Common/Shared/fast_telemetry_publisher
sys log-config destination remote-high-speed-log /Common/Shared/fast_telemetry_hsl
sys log-config destination splunk /Common/Shared/fast_telemetry_formatted
```

### Steps To Reproduce

Install FAST extension.

### Expected Behavior

FAST does not create telemetry streaming related objects in `/Common/Shared`, especially when telemetry streaming is not even installed.
In addition creation is configurable by a flag like `enable_telemetry`.

### Actual Behavior

FAST always creates configuration objects.

**Comment by joelkeener** [comment]
You can create objects in /Common/Shared with AS3 before and/or after FAST creates its TS objects there. 

AS3 will be the source of truth in this case, and we just stitch our objects into their existing declaration.

Please let me know if you have any questions about this.

**Comment by joelkeener** [comment]
You will have to include the Shared config in your AS3 declaration whenever you update it, but if you forget the TS objects, they will get stitched in each time the FAST config is saved.

**Comment by simonkowallik** [comment]
@joelkeener thank you for the detailed information. Knowing that we can use other means to create objects in `/Common/Shared` is fine to me.

**Comment by shyawnkarim** [comment]
Closing. We will update our documentation and add some troubleshooting steps when this situation occurs.

**Comment by shyawnkarim** [comment]
Closing. Our documentation was updated with [Release 1.23.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.23.0).
