### ISSUE TITLE
If template is uploaded with space between the name, unable to delete

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-appsvcs-templates#123]
### Environment
 * FAST RPM Version: f5-appsvcs-templates-1.24.0-1.noarch
 * BIG-IP Version: 16.1.0

Upload new template with a space in the name/folder 
[test template.zip](https://github.com/F5Networks/f5-appsvcs-templates/files/10981269/test.template.zip)
which works, try to delete and you get this error:
Failed to delete test template:
Failed to get data from /mgmt/shared/fast/templatesets/test template: 404 Not Found
failed to find template set: test%20template

### Expected Behavior
If spaces aren't allowed in the template folder they should be rejected before creation.

**Comment by shyawnkarim** [comment]
Closing. 

If you would still like assistance, please leave a comment here and I'll reopen the issue.

**Comment by shyawnkarim** [comment]
This issue was resolved with [Release 1.25.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.25.0).
