### ISSUE TITLE
Reusing pool delivers error "The requested Node .... already exists in partition tenant1

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-templates#128]
### Environment
 * FAST RPM Version: 1.24
 * BIG-IP Version: 16.1.3.2

### Summary
One deploying a simple-http-app using the simple-http template I define a pool in tenant1.

When deploying another application using template HTTP Application Template in the same tenant 1 and selecting the already existing Pool created at the simple-http template deployment, the deployment of the HTTP Application template fails with the following error "01020066:3: The requested Node (/tenant1/a.b.c.d) already exists in partition tenant1."

### Steps To Reproduce
1. Deploy simple-http template in tenant1
2. Deploy HTTP Application Template in tenant1 and select existing Pool (created from the previous pool)
3. Deployment of HTTP Application fails.

### Expected Behavior
I would expect that if I am allowed to select an existing pool from the drop down menu and the pool is within the same tenant, that the template deployment should succeed.

### Actual Behavior
Selecting an existing pool and deploying the template it fails with this error: 01020066:3: The requested Node (/tenant1/a.b.c.d) already exists in partition tenant1.

**Comment by shyawnkarim** [comment]
The simple_http template creates a new pool, using the app name, for every app deployed, which can be seen in the schema:

{
  "class": "ADC",
  "schemaVersion": "3.0.0",
  "{{tenant_name}}": {
    "class": "Tenant",
    "{{application_name}}": {
      "class": "Application",
      "template": "http",
      "serviceMain": {
        "class": "Service_HTTP",
        "virtualPort": {{virtual_port::integer}},
        "virtualAddresses": ["{{virtual_address}}"],
        "pool": "{{application_name}}_web_pool"
      },
      "{{application_name}}_web_pool": {
        "class": "Pool",
        "monitors": [
          "http"
        ],
        "members": [
          {
            "servicePort": {{server_port::integer}},
            "serverAddresses": {{server_addresses::array}}
          }
        ]
      }
    }
  }
}

Did you customize this template so that you can select an existing pool?

**Comment by shyawnkarim** [comment]
I was able to deploy first the simple-http template, that creates a pool, and then deploy http-application-template to the same tenant and select the existing pool. Both deployed without errors.

Maybe there is something else going on with your templates?
