### ISSUE TITLE
HTTP Application Template - set Ingress Topology to LAN fails

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-templates#129]
### Environment
 * FAST RPM Version: 1.24
 * BIG-IP Version: 16.1.2.1

### Summary
When using "HTTP Application Template" and selecting LAN as the Ingress Topology option and Deploy. Checking the application it has changed back to the default value WAN. 

Checking the BIG-IP Local Traffic configuration at Virtual Servers it does have "f5-tcp-wan" configured.

### Steps To Reproduce
List the steps to reproduce the behavior:
1. In the FAST GUI select "HTTP Application Template".
2. Enter the required values to be able to deploy the template.
3. Change the 'Ingress Toplogy' value from 'WAN' to 'LAN'.
4. Hit Deploy.
5. Once deployed, select the application and check the 'Ingress Topology' value.
6. Check the related VS client tcp profile.

You will notice that the selected LAN value is reverted back to WAN upon Deploying the template.

### Expected Behavior
When selecting LAN as the Ingress Topology option one will expect 'f5-tcp-lan' configured as the client tcp profile in the virtual server and not 'f5-tcp-wan'.

### Actual Behavior
When selecting LAN as the Ingress Topology value, the template will not configure this but configure the default value of WAN once the template gets deployed.

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. It's now being tracked internally with ID, EC-177.

**Comment by joelkeener** [comment]
Hello @gwolfis, this appears to be an AS3 bug, but you can work around it in one of two ways:

1. check the "Common TCP Profile" box, and then select LAN from the "Common Network Topology" list -- which will create a lan profile that is used on both Ingress and Egress
2. select something other than the default, LAN, for the "Egress Topology" when "Common TCP Profile" is unchecked

The AS3 bug occurs when you try to use the same value in the ingress as you do in the egress for the [Service_HTTP_profileTCP](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-http-profiletcp) object.
