### ISSUE TITLE
auto refresh tabs data in gui

### ISSUE THREAD

**Issue by DumpySquare** [F5Networks/f5-appsvcs-templates#13]
### Environment
 * FAST RPM Version: 1.1.0
 * BIG-IP Version:  14.1.2.3

### Summary
when developing/uploading templates, deploying applications, and deleting items (apps/templates) via the api, it would be nice if the gui would refresh when data is updated.

### Steps To Reproduce
deploy application via api, no update to deploy apps in gui without user interaction

### Expected Behavior
refresh tab information when task job completes (ie, deploy app, remove app, upload template, remove template set).

Or even update deploy log when api task is started, just like deploying an application via the gui

### Actual Behavior
gui does not show any response to API calls unless user navigates to a new page

Sorry, probably not a bug, but more of an enhancement..

**Comment by zinkem5** [comment]
At this time, we do not plan to add any notification or event features.
