### ISSUE TITLE
members_server support?

### ISSUE THREAD

**Issue by PatricDahl** [F5Networks/f5-appsvcs-templates#130]
### Is your feature request related to a problem? Please describe.
Is there support for below declaration in FAST template?

> "members": [
  {
    "servicePort": 443,
    "servers": [
      {
      "name": "server01",
      "address": "192.0.2.1"
      },
      {
      "name": "server02",
      "address": "192.0.2.2"
      }
    ]
  }

> ]

## Can only see support for alternative such as:
"serverAddresses": {{server_addresses::array}}

### Describe the solution you'd like
Any solution that make it possible to create FAST template and pass variables into.

**Comment by shyawnkarim** [comment]
Do you still need help with this? FAST supports everything AS3 can do. We have documentation on how to create FAST templates here:

[https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/template-authoring.html](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/template-authoring.html)

**Comment by shyawnkarim** [comment]
Closing.

If you would still like assistance, please leave a comment here and I'll reopen the issue.
