### ISSUE TITLE
[RFE]expose "deploy" tab views through API

### ISSUE THREAD

**Issue by DumpySquare** [F5Networks/f5-appsvcs-templates#15]
### Is your feature request related to a problem? Please describe.

Under the "Deploy" tab of the FAST GUI, there are four buttons along the bottom next to the submit button, it would be nice if those functions were exposed via the API
  - "View Rendered" - Would allow a user to see what the fast template will produce programatically without actually deploying anything.  This would be extremely helpful for development, testing, and troubleshooting.
  - "View Inputs" - Would also help show users and programs quickly and easily understand what parameters are needed to deploy the application
  - "View Schema" - Would help template authors understand how FAST is interpreting the template during authoring and provide some insight to a deeper understanding and use of FAST templates
  - "View Template" - Could be an easy way for a user to programatically see just the template and nothing else

### Describe the solution you'd like

Expose the gui deploy tab buttons as API endpoints or template endpoint parameters.  

### Describe alternatives you've considered

There is no alternative at this time.  This would just expand the ways developers and users could interact with the system for automation purposes

**Comment by shyawnkarim** [comment]
Thanks for suggesting this enhancement. We are now tracking it with internal ID MYSTIQUE-336.

**Comment by delgadillo22** [comment]
This functionality is already exposed in the FAST CLI -- can you provide some use-cases for this RFE?

**Comment by DumpySquare** [comment]
Sure.  This use case is for use through the ATC ILX RPM running on the F5 where templates are also located.  This would provide a mechanism for external tools to utilize the templating functionality and provide visibility for user understanding/troubleshooting (ie. a user could test the output of a template and fast engine on an F5 without having to log into the UI)

**Comment by shyawnkarim** [comment]
Closing, since /render endpoint was added in [Release 1.8.](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.8.0)
