### ISSUE TITLE
[RFE] support access policy templating (APM)

### ISSUE THREAD

**Issue by DumpySquare** [F5Networks/f5-appsvcs-templates#17]
As part of the effort and promise to support important existing iApps, the user needs to be able to deploy applications that utilize APM.  I think this could be accomplished in with the following flow:

- allow direct file references for addition file types within the template set folder
  - At first, this would be just a static file, which fast could templatize some parameters within, like object names
  - Utilizing the power of FAST, I can see this growing into some rather powerful apm policy options
  - related to #16 requesting this specific feature
- configure FAST to understand that it is an apm policy, consume the policy at FAST template deployment, swap out parameters/variables as needed and host the resulting policy as an api endpoint
- then FAST could automatically reference the policy in the as3 declaration it sends by pointing to the URL FAST is hosting for the rendered apm policy
  - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/access-related.html

This could also be used for ASM policies... :)

**Comment by zinkem5** [comment]
FAST's vector to get supported access to BIG-IP features is AS3.

AS3 will need to support APM/ASM before we get APM/ASM support in FAST.

**Comment by DumpySquare** [comment]
I'm not asking for anything outside of what AS3 already supports for APM/ASM policies, which is local ltm reference or URL reference.

What I am asking for, is a way for APM/ASM policies be included in the fast template directory, and referenced in a template (hopefully with fast variables).  This would remove the road block for the netOps user to find some place to host the policy on an HTTP endpoint somewhere.

**Comment by raZorTT** [comment]
Hi

Can this please be re-opened? Is there a chance we can have the template extended to allow referencing an existing policy or URL reference as @DumpySquare mentioned above?
