### ISSUE TITLE
unselecting persistence, still makes persistence

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-templates#23]
When using bigip-fast-templates/http.

Deselecting persistence in the template does not result in no persistence when deploying the template.
Checking the VS config, the default persistence profile is still set to cookie. 

### Environment
 * FAST RPM Version: 1.3.0
 * BIG-IP Version: 15.1.0.4

### Steps To Reproduce
Deploy the mentioned template and deselect persistence. 

### Expected Behavior
Unselecting persistence in the template should give that traffic gets directed based on the selected load balancing algorithm.

### Actual Behavior
Persistence keeps being selected, though it is unselected in the template.

**Comment by zinkem5** [comment]
We are looking into this, stay tuned.

**Comment by mstokes-f5** [comment]
I cannot reproduce this using FAST v1.5.0. When the template is deployed with Persistence deselected, the Default and Fallback Persistence Profiles are getting set to None (as reported by the BIG-IP GUI):

![image](https://user-images.githubusercontent.com/61211686/99843891-16225600-2b27-11eb-9b5b-74c0c95689dc.png)

Please try using FAST v1.5.0 and see if you are still experiencing this issue. If you are, please feel free to re-open this issue.
