### ISSUE TITLE
Upgraded to 1.4 Error Fetching Applications

### ISSUE THREAD

**Issue by markstubb** [F5Networks/f5-appsvcs-templates#25]
I was running 1.2 and wanted to upgrade to 1.4. I guessed that I just needed to upload the rpm like I was installing from scratch and it prompted me that it was an upgrade.  There's no 'upgrade' documentation so I just swagged at that.  After upgrading, I received the following error trying to click on the 'F5 Application Services Templates' link

Error fetching applications: Failed to get data from /mgmt/shared/fast/applications: 400 Bad Request
remoteSender:xxx.xxx.xxx.xxx, method:GET 

Figured i did something wrong so I completely removed the extension and reinstalled from scratch.  Same error.

On 15.1.0.4 big-ip.  Haven't deployed any apps using FAST yet. Warming up to it.

**Comment by mstokes-f5** [comment]
In the future, please use one of the supplied GitHub issue templates when filing a new issue for FAST. Filling out the questions in these templates helps us better understand and solve the issue.

As for the issue itself, FAST upgrades on minor versions (e.g., 1.x) are intended to be a safe operation as are upgrades of the bigip-fast-templates template set. As for the error you are encountering, we will need more information. First off, is AS3 installed on the BIG-IP? FAST requires AS3. Can you reach the `/mgmt/shared/fast/info` endpoint? It could be that the FAST iApps LX REST worker was not ready to receive requests yet. This last issue was addressed with FAST v1.5.0.

**Comment by shyawnkarim** [comment]
Closing.

Please reopen if you are still experiencing issues.
