### ISSUE TITLE
[RFE] Support handlebars for templating

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-templates#27]
### Is your feature request related to a problem? Please describe.
I'm unable to use mustache to template my AS3 declaration

### Describe the solution you'd like
Use a templating system that supports more features
### Describe alternatives you've considered
Not using FAST.

### Additional context
This outlines what I'm trying to do pretty well, generate an output of 
```
["app001": {"class":Pool"},
"app002": {"class:"Pool"},
"app003": {"class":"Pool"}]
```
using mustache.js you can have a template of 
```
...
    [{{ #services }}
    "{{ . }}": {"class": "Pool"},
    {{ /services }}]
...
```
This results in 
```
[
"app001": {"class": "Pool"},

"app002": {"class": "Pool"},

"app003": {"class": "Pool"},
]
```
the trailing comma prevents this from being usable.  You could add a bogus pool entry, but it seems like a poor workaround to the core issue of the template.

It seems like handlbar could potentially solve this by giving you more features based on the following post: https://stackoverflow.com/questions/6114435/in-mustache-templating-is-there-an-elegant-way-of-expressing-a-comma-separated-l

another possible workaround would be to generate the template in YAML and have it convert to JS, but that seems weird.

**Comment by zinkem** [comment]
Switching to handlebars will render this project a waste of money. 🤷

**Comment by chen23** [comment]
@zinkem what alternative would you recommend?

**Comment by zinkem** [comment]
Eric we wen't over this during the summer, we had the dangling comma
problem solved. If there was a regression, it's no longer my problem.

**Comment by chen23** [comment]
@zinkem if you have an example that would be great. Thank you.

**Comment by zinkem** [comment]
Do you really wanna do this in public?

**Comment by chen23** [comment]
I sent you a message on Teams.

**Comment by zinkem** [comment]
I was terminated on November 6th.

**Comment by chen23** [comment]
@zinkem Hey I am sorry to hear that. I had no idea.

**Comment by zinkem** [comment]
Apparently nobody sent the memo. 

I would be more than happy to provide a consult in the new year, provided there is no conflict of interest, but the price will be high. 

The AS3 team is full of extremely intelligent people, and the developers I worked with understood the problems associated with AS3 and FAST, and the _parsing_ problems associated with popular templating solutions.

**Comment by shyawnkarim** [comment]
Closing.

Please open a new issue if you would like to discuss this further.
