### ISSUE TITLE
Deploy Log Tag Logs Me off the BIG-IP

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-appsvcs-templates#3]
### Environment
 * FAST RPM Version: 1.0.0
 * BIG-IP Version: 15.0.1

### Summary
While trying to troubleshoot a FAST issue I clicked on the Deploy Log tab and I'm logged out of the BIG-IP GUI.  I can reproduce this issue every time I log back in and click on the Deploy Log tab.  

### Steps To Reproduce
List the steps to reproduce the behavior:
Click on the Deploy Log tab

### Expected Behavior
See deployment logs

### Actual Behavior
logged out of the BIG-IP GUI

**Comment by codygreen** [comment]
rebooting resolved this issue

**Comment by codygreen** [comment]
Repoening, issue has started again after a failed deployment

**Comment by codygreen** [comment]
I've noticed the issue is not isolated to the Deploy Log tab.

**Comment by zinkem5** [comment]
We are looking into this, it is currently believed to be a limitation of the TMOS platform.

**Comment by chen23** [comment]
you could try to either:

1. disable "Require A Consistent Inbound IP For the Entire Web Session" under Systems -> Prefences
1. use a different admin user when accessing FAST than the one logged in

it's hard to reproduce, but it seems more usable using one of these two methods.  this is from trial and error.

**Comment by zinkem5** [comment]
I think the consensus is that this is going to be difficult to fix in the product, current recommendation is to follow @chen23 's configuration tweaks.
