### ISSUE TITLE
[RFE] FAST ADFS Template for MS-ADFSPIP support with APM

### ISSUE THREAD

**Issue by thomas-rd21** [F5Networks/f5-appsvcs-templates#32]
### Is your feature request related to a problem? Please describe.

iApp for ADFS supports F5 APM as a replacement for MS WAP.
But iApp support for ADFS is terminated to 03/31/21.
https://support.f5.com/csp/article/K13422

### Describe the solution you'd like

A fully supported FAST replacement for the ADFS iApp.
Currently, there is only loadbalancing supported in FAST for ADFS but not APM with MS-ADFSPIP as replacement for MS WAP.

### Describe alternatives you've considered

Not using FAST and configure it by hand as descriped here:
https://techdocs.f5.com/en-us/bigip-15-1-0/big-ip-access-policy-manager-third-party-integration/apm-as-an-ad-fs-proxy.html

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue. We are now tracking this enhancement internally with ID MYSTIQUE-348.

**Comment by delgadillo22** [comment]
APM support is out of scope of FAST templates due to API limitations.
Thus the requested APM support in the ADFS FAST template is out of scope and is not part of our FAST roadmap.
The APM limitation is not unique to the ADFS FAST template; it applies to all FAST templates.

**Comment by shyawnkarim** [comment]
We will update our documentation to include "APM Guidance for ADFS" that references the [ADFS iApp Deployment Guide on pages 10-13](https://www.f5.com/pdf/deployment-guides/microsoft-adfs-dg.pdf ).

**Comment by shyawnkarim** [comment]
Closing.

We have updated our documentation to include links on APM Guidance in [Release 1.8](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.8.0) and can be viewed on [F5 Cloud Docs](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/APM-guidance.html?highlight=adfs).
