### ISSUE TITLE
FAST v1.6 does not display in the GUI

### ISSUE THREAD

**Issue by inoue-hi** [F5Networks/f5-appsvcs-templates#33]
### Environment
 * FAST RPM Version: f5-appsvcs-templates-1.6.0-1.noarch.rpm
 * BIG-IP Version: v14.1.2.6, v15.1.2

### Summary
Reproducibility: yes
Severity: Sev 3 Perfomance Degraded
Impact: Can not use F5 Application Service Templates

When following this video
    https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/

... and using FAST v1.6, the customer does not see FAST show up in the Applications LX page.

### Steps To Reproduce

Install following packages via GUI
f5-appsvcs-3.25.0-3.noarch.rpm
f5-appsvcs-templates-1.6.0-1.noarch.rpm
and touch /var/config/rest/iapps/enable

F5 Application Services Templates is not shown up under 
GUI iApps-Application Services-Application LX- Application Service list

Downgrade to f5-appsvcs-templates-1.5.0-1.noarch.rpm,  then it shows up
Upgrade to f5-appsvcs-templates-1.6.0-1.noarch.rpm, it still show up.

Undeploy F5 Application Services Templates, and Delete
Delete f5-appsvs-template v1.6.0 rpm package

then install f5-appsvcs-templates-1.6.0-1.noarch.rpm again, F5 Application Services Templates is not shown up again.

### Expected Behavior

F5 Application Services Templates should show up under 
GUI iApps-Application Services-Application LX- Application Service list, after installing f5-appsvcs-templates-1.6.0-1.noarch.rpm

### Actual Behavior

F5 Application Services Templates is NOT shown up under GUI iApps-Application Services-Application LX- Application Service list, after installing f5-appsvcs-templates-1.6.0-1.noarch.rpm

**Comment by delgadillo22** [comment]
Thanks for the report. This issue has been resolved in FAST 1.6.1 which has been posted here in GitHub.
