### ISSUE TITLE
bigip-fast-template/microsoft-exchange doesn't accept route-domain in IP address fields

### ISSUE THREAD

**Issue by bss-markus-schulze** [F5Networks/f5-appsvcs-templates#34]
### Environment
 * FAST RPM Version: 3.25.3
 * BIG-IP Version: 14.1.3
 * FAST Template Version: 1.60

### Summary
The bigip-fast-template/microsoft-exchange denies IP addresses with route-domain identifiers (%<route-doomain>) attached.
The error message is: Value must be a valid IPv4 address in the form of 4 numbers between 0 and 255, separated by dots.

### Steps To Reproduce
Enter an IP address with route-domain-identifier

### Expected Behavior
Route domain identifier should be accepted in IP address fields.

### Actual Behavior
Route domain identifier in IP address fiels generates error message.

![image](https://user-images.githubusercontent.com/78405591/106566594-c998c500-6530-11eb-8804-a82ebc43e901.png)

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-343.

**Comment by shyawnkarim** [comment]
This enhancement was included with R[elease 1.10](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.10.0).
