### ISSUE TITLE
Add Bot Defense profiles to FAST HTTP templates

### ISSUE THREAD

**Issue by geschdan** [F5Networks/f5-appsvcs-templates#35]
### Is your feature request related to a problem? Please describe.
Bot Defense profiles not available in iApps or FAST templates

### Describe the solution you'd like
Please allow selection of the Bot Defense Profile in the HTTP FAST template. (we understand that iApps will be deprecated, so not much use addressing it there I would imagine)

### Describe alternatives you've considered
Turning off strict updates (yah, that stinks)

### Additional context
Configuration inconsistencies, inability to apply F5 technologies when using iApps or FAST templates.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this enhancement internally with ID MYSTIQUE-344.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.14.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.14.0).
