### ISSUE TITLE
bigip-fast-templates/microsoft_iis TLS Certificate & Key drop-down boxes do not show my cert

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-appsvcs-templates#36]
### Environment
 * FAST RPM Version: 1.6.1
 * BIG-IP Version: 15.1.2.1

### Summary
Cannot select new TLS certificates in the microsoft_iis template (template only offers the default pre-installed F5 certs).
It works as expected (I can select my cert) if I create the configuration using the "bigip-fast-templates/http" template instead of the iis template.
This problem was repeated on a Virtual Edition as well as on an i2800 physical appliance running the same software version.

### Steps To Reproduce
1 - Import your cert via the "System >> Certificate Management >> Traffic Certificate Management" page
2 - Go to "iApps >> Application Services >> Applications LX" and click on "F5 Application Services Templates"
3 - Click on "Deploy"
4 - Select "bigip-fast-templates/microsoft_iis"
3- Leave "FAST-Generated TLS Server Profile" enabled and "try to" chose your cert and key under the TLS cert Certificate and TLS Key sections (only the default F5 certs show up). 

### Expected Behavior
I expect to be able to select my own certs for the IIS web application I deploy via this template.

### Actual Behavior
I am forced to select the wrong certs.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this internally with ID MYSTIQUE-345.

**Comment by danielcayer** [comment]
I am observing the same situation with a new custom template I just created. I believe the issue to be related with the fact that drop-down is making use of the enumFromBigip feature? It would seem that the enumerated values are somehow cached when the FAST RPM is installed or when the template is initially deployed and new items created afterwards do not trigger a "refresh" of the presented enumFromBigip values?

**Comment by danielcayer** [comment]
Update: newly released FAST v1.7 appears to have resolved this issue.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.7.](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.7.0)
