### ISSUE TITLE
Provide libs/modules for Angular

### ISSUE THREAD

**Issue by johnalam** [F5Networks/f5-appsvcs-templates#38]
### Is your feature request related to a problem? Please describe.
Would like to be able to use the libraries from an Angular App.  Would like to collect user input using custom UI , render an AS3 declaration and submit it directly to devices.

### Describe the solution you'd like
Need the functions in fast cli callable from an Angular App.

### Describe alternatives you've considered
Considered using node.js as a backend processor but that makes the Angular App more complex and larger.

**Comment by shyawnkarim** [comment]
Thanks for requesting this enhancement. We are now tracking it internally with ID MYSTIQUE-347.

**Comment by delgadillo22** [comment]
Hi John, FAST integration with Angular is out of scope. This is not planned for our roadmap.

**Comment by mstokes-f5** [comment]
@johnalam the functions from the FAST CLI are available as part of the [f5-fast-core NPM package](https://www.npmjs.com/package/@f5devcentral/f5-fast-core), which should be usable from Angular.

**Comment by shyawnkarim** [comment]
Closing.

Please reopen if there is any further input on the issue.
