### ISSUE TITLE
Error after attempting to add a custom template set

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-appsvcs-templates#40]
### Environment
 * FAST RPM Version: 1.6.1
 * BIG-IP Version: 15.1.0 Build 0.0.31 Final

### Summary
I cloned the bigip-fast-templates set, created a new template and zipped into a new custom template set.
I attempted to add my custom.zip template set via the "iApps  ››  Application Services : Applications LX >> F5 Application Services Templates/Templates" page, but received an error and can no loger use any FAST templates. I get the following error message:

*Template errors were found:
stdout maxBuffer exceeded*

### Steps To Reproduce
List the steps to reproduce the behavior: 
Login as admin and browse to "iApps  ››  Application Services : Applications LX >> F5 Application Services Templates/Templates".

### Expected Behavior

The list of installed templates should appear.

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

None of the installed templates are listed. Instead, I get the following error message:

*Template errors were found:
stdout maxBuffer exceeded*

![image](https://user-images.githubusercontent.com/28303815/108558839-84161f00-72c8-11eb-92f2-713c0556bf60.png)

**Comment by danielcayer** [comment]
I haven't been able to find a way to recover from the error. Reinstalling the RPM packages and rebooting the BIG-IP appliance does not allow me to use FAST.

I deployed a new BIG-IP VE and was able to successfully install my custom template set after manually deleting the pre-installed "bigip-fast-templates".

**Comment by delgadillo22** [comment]
Thanks - we are tracking this bug internally as MYSTIQUE-254.

**Comment by shyawnkarim** [comment]
Closing.

This issue has been resolved with [Release 1.8](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.8.0).
