### ISSUE TITLE
Exchange template does not prompt for virtual ip address

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-appsvcs-templates#42]
### Environment
 * FAST RPM Version: 1.7
 * BIG-IP Version: 15.1.0

### Summary
The Exchange template does not prompt for the virtual server IP address when the "Common VIP" setting is enabled.

### Steps To Reproduce
Go to "Apps  ››  Application Services : Applications LX >> F5 Application Services Templates >> Deploy >> bigip-fast-tempaltes/microsoft_exchange" and observe that there is no option to specify the VIP address.

### Expected Behavior
An  option for specifying the VIP address should be visible.

### Actual Behavior
The  option for specifying the VIP address is not visible.

**Comment by delgadillo22** [comment]
Thank you -- we are tracking this internally as MYSTIQUE-355

**Comment by frslater** [comment]
Fixed in patch Release 1.8.1
