### ISSUE TITLE
Custom Template set named with prefix "bigip-fast-templates" ,also adds default templates to custom template set

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-templates#45]
### Environment
* FAST RPM Version:1.6.1
* BIG-IP Version:15.1.0

### Summary
Custom Template set named with prefix "bigip-fast-templates" ,also adds default templates to custom template set

### Steps To Reproduce
List the steps to reproduce the behavior:
1.Upload and install custom Fast template set with name "bigip-fast-templates-service-discovery.zip".
-Application services ->Applications Lx ->F5 Application Services Templates ->Templates ->Add Template set

2.Verify templates added under custom template set "bigip-fast-templates-service-discovery"
Application services ->Applications Lx ->F5 Application Services Templates -> Deploy ->bigip-fast-templates-service-discovery

### Expected Behavior
Only Custom templates should be added under a custom template set named with prefix "bigip-fast-templates".

### Actual Behavior
Custom Template set named with prefix "bigip-fast-templates" ,also adds default templates also to custom template set

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this internally with ID MYSTIQUE-359.

**Comment by shyawnkarim** [comment]
Closing.

This issue has been resolved with [Release 1.8.](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.8.0)
