### ISSUE TITLE
Unable to load templates

### ISSUE THREAD

**Issue by DJR-FP** [F5Networks/f5-appsvcs-templates#46]
### Environment
 * FAST RPM Version: f5-appsvcs-templates-1.7.1-1.noarch
 * BIG-IP Version: 15.1.2.1-0.0.10  VE

### Summary
Include information about the reproducibility and the severity/impact of the issue.
Installed both AS3 and FAST templates on my lab F5, works well on v14, but although the install looks to be good, when trying to open/deploy I have no templates, just a spinning circle nothing is displayed .

### Steps To Reproduce
List the steps to reproduce the behavior:
I can easily reproduce this by installing and viewing the templates again .
![f5 templates](https://user-images.githubusercontent.com/33313991/111617221-c143d300-87da-11eb-8396-916a48d26f1f.png)

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I was able to reproduce this bug and it is now being tracked internally with ID MYSTIQUE-360.

**Comment by nwehrman** [comment]
Tested and this is being seen in v14.x (latest), v15.x (latest), and v16.x (latest). Any eta on when these will be working? the 1.7.0 work fine.

**Comment by shyawnkarim** [comment]
Closing.

This issue has been resolved with [Release 1.8](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.8.0).
