### ISSUE TITLE
how to - render html preview from template in FAST with additional schema references

### ISSUE THREAD

**Issue by DumpySquare** [F5Networks/f5-appsvcs-templates#47]
in the vscode-f5 extension, there is a process to view the HTML preview of a template, which is really cool to see how the template will look to the user.  This process can take raw template text (mst/yaml) and run it through fast-core to produce the HTML preview

This is where we pick up the text from the editor:  https://github.com/f5devcentral/vscode-f5/blob/2e18daaa8c3baaeae58ac2bd3b4686b2e91f7287/src/extension.ts#L758

this is where we load the template into the fast engine to produce the HTML preview:  https://github.com/f5devcentral/vscode-f5/blob/2e18daaa8c3baaeae58ac2bd3b4686b2e91f7287/src/editorViews/fastWebView.ts#L58

The problem we are running into is when the template references an external file, like an additional schema.  An example is the bigip-fast-templates/http.

Is there a way to get that additional schema via API or can we look at including it in the template definition after the template set is imported?

![image](https://user-images.githubusercontent.com/3260966/112179785-fbd9b100-8bc8-11eb-98c5-5a37c991af78.png)

**Comment by delgadillo22** [comment]
Hi, we are tracking this request internally as MYSTIQUE-361. Need some time to review.

**Comment by mstokes-f5** [comment]
@DumpySquare is this still an issue for you?

Taking a look at the line above (including the recent code), I see that you are calling `Template.loadYaml()` without supplying a TemplateProvider nor a SchemaProvider so `Template.loadYaml()` does not have a means of getting external files. If loading from a TemplateProvider (e.g., `FsTemplateProvider`) these already get passed into the `Template.loadYaml()` call.

**Comment by DumpySquare** [comment]
Hi @mstokes-f5, this is not an issue for me per-se, but this really limits what the extension can do with fast templates.

I thought it was a nice and convenient way for fast template authors to test the output of some of the more complicated f5 authored templates.  

Can it load a template from a file location so it knows where to get there references?

I'm open to suggestion on a better way to test templates during the authoring process without having to load them into a bigip to see the UI.

**Comment by mstokes-f5** [comment]
For this specific problem, you need to supply a `SchemaProvider`, which is documented [here](https://github.com/f5devcentral/f5-fast-core#loading-with-type-schema). For just loading a template from disk and having all the providers hooked up, use a `TemplateProvider` (either `FsTemplateProvider` or `FsSingleTemplateProvider` as documented [here](https://github.com/f5devcentral/f5-fast-core#using-a-templateprovider).

**Comment by DumpySquare** [comment]
Got it.  thanks.  I'll take a loot at that.
