### ISSUE TITLE
Cannot choose custom persistence profiles with FAST/http template

### ISSUE THREAD

**Issue by Jeremy-Universal** [F5Networks/f5-appsvcs-templates#48]
### Environment
 * FAST RPM Version: f5-appsvcs-templates-1.7.0-1.noarch
 * BIG-IP Version: BIG-IP 14.1.2.6 Build 0.0.2 Point Release 6
--

### Summary
When deploying with bigip-fast-templates/http only the default persistence types are available

![image](https://user-images.githubusercontent.com/81439802/112680162-66962100-8e43-11eb-8bda-f26c9dfeb04f.png)

### Steps To Reproduce
List the steps to reproduce the behavior:
1. Deploy->BigIP-Fast-Templates/http
2. Fill in Tenant, Application Name, IP address, etc
3. Select the check box for Persistence
4. Only the built-in persistent types are selectable

### Expected Behavior
I expect to be able to select custom persistence profiles located within the Common or any other Partition

### Actual Behavior
The drop down for persistence type only offers the out-of-the-box options

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are tracking it internally with ID MYSTIQUE-368.

**Comment by shyawnkarim** [comment]
This fix for this issue was included with [Release 1.10](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.10.0).

**Comment by jodr5786** [comment]
We just upgraded our test LTM to 1.11.0, and are getting an error when trying to choose a custom persistence profile.
![image](https://user-images.githubusercontent.com/27083437/129076961-34b4c391-d0e8-466d-891c-35bf7464a5be.png)
![image](https://user-images.githubusercontent.com/27083437/129076976-3227d968-0ab8-4eab-8784-038aabd617ca.png)

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. We are now tracking it internally with ID MYSTIQUE-454.
