### ISSUE TITLE
Unable to delete custom template set as FAST created partition reference is not removed if partition deleted using AS3 endpoint. 

### ISSUE THREAD

**Issue by KonikaChaurasiya-GSLab** [F5Networks/f5-appsvcs-templates#49]
### Environment
 * FAST RPM Version: 1.7.0
 * BIG-IP Version: 15.1.0.5

### Summary
Unable to delete custom template set as FAST created partition reference is not removed if partition deleted using AS3 endpoint. 

### Steps To Reproduce
1. Create FAST partition/application using a custom FAST template set using API https://<BIG-IP>/mgmt/shared/fast/applications
2. Delete the same partition using the AS3 API **https://<BIGIP:port>/mgmt/shared/appsvcs/declare/<partitionname>**
3. Delete custom template set using the FAST API  **https://<BIG-IP>/mgmt/shared/fast/templatesets/<custom_template set_name>**.

### Expected Behavior
It should delete the template set since no partitions/applications are available which are created using that template set

### Actual Behavior
Unable to delete custom template set as FAST created partition reference is not removed if partition deleted using AS3 endpoint. Getting below error:
"message": "Cannot delete template set <custom_template set_name>, it is being used by:\n[\"<partition_name>/<app_name>\"]"

**Comment by delgadillo22** [comment]
Thanks for the report. We are tracking this internally as MYSTIQUE-367.

**Comment by delgadillo22** [comment]
Hello, creating an app with FAST and then deleting it directly with AS3 is not a recommended nor supported practice. 
Once you deploy an app with FAST, you must manage the app's lifecycle with FAST thereafter.

**Comment by shyawnkarim** [comment]
Closing since this is unsupported behavior.
