### ISSUE TITLE
Multi-select list boxes are not supported

### ISSUE THREAD

**Issue by F5Debbie** [F5Networks/f5-appsvcs-templates#5]
Currently FAST does not support templates with multi-select list boxes.

**Comment by mstokes-f5** [comment]
Support for these have since been added with FAST v1.4.0. Documentation for this feature can be found [here](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/advanced-features.html#multiple-choice-lists).
