### ISSUE TITLE
Nodes won't be put into specified tenant/partition (SharePoint & Exchange)

### ISSUE THREAD

**Issue by grundbacher** [F5Networks/f5-appsvcs-templates#50]
### Environment
 * FAST RPM Version: 1.8.0
 * BIG-IP Version: 16.0.1

### Summary
When deploying a SharePoint or Exchange template, the nodes generated will stay in the partition common. The other objects though will be put into the partition specified under "tenant".

### Expected Behavior
I think it would make sense to also operate the nodes under the same partition/tenant where the other objects were generated.

**Comment by shyawnkarim** [comment]
This is actually working as designed. If you would like the nodes to not be shared you can change "shareNodes: true" to "shareNode: false" in the template.
