### ISSUE TITLE
Navigating to FAST UI on BIG-IP pops-up "Your login credentials are no longer valid" window frequently even after we login with correct credentials.

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-templates#52]
### Environment
 * FAST RPM Version:1.8.0
 * BIG-IP Version:15.1.2.1 

### Summary
Navigating to FAST UI on BIG-IP pop-up "Your login credentials are no longer valid" window frequently even though we login with correct credentials

### Steps To Reproduce
List the steps to reproduce the behavior:
1.Intall the AS3 and Fast Template RPM package on BIG-IP
2.Open Fast UI iApps  ››  Application Services : Applications LX ›› F5 Application Services Templates. Login with credentials and verify fast templates.
3.Navigate to Local Traffic  ››  Virtual Servers : Virtual Server List
3.Post fast application create declaration on BIG-IP
https://<<BIG-IP>>/mgmt/shared/fast/applications
4.Navigate to FAST UI iApps  ››  Application Services : Applications LX ›› F5 Application Services Templates. Login with credentials and verify fast templates.

### Expected Behavior
When FAST operation is performed, BIG-IP login screen should not re-appear since the BIG-IP is already logged in with correct credentials

### Actual Behavior
Navigating to FAST UI on BIG-IP pop-up "Your login credentials are no longer valid" window frequently even though we login with correct credentials.

![loginerror (2)](https://user-images.githubusercontent.com/61869155/115692507-ae459500-a37c-11eb-90bf-0bad8601cc3e.png)

**Comment by DumpySquare** [comment]
I've been seeing this also

**Comment by grf5** [comment]
I was this several times during testing last night, as well.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-397.

**Comment by shyawnkarim** [comment]
The fix for this was included with [Release 1.10](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.10.0).
