### ISSUE TITLE
Slow ramp field is missing in the required section of "bigip-fast-templates/http" template schema

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-templates#53]
### Environment
 * FAST RPM Version: 1.8.0
 * BIG-IP Version: 15.1.2.1 

### Summary
Slow ramp field is missing in the required section of "bigip-fast-templates/http" template schema. As we are not able to deploy the application without slow ramp field.

### Steps To Reproduce
1.Post an declaration to deploy an application using FAST without slow ramp field
API-
https://<BIG-IP>/mgmt/shared/fast/applications

### Expected Behavior
User should able to deploy an application without slow_ramp_time as it is not present in the required section of template schema.

### Actual Behavior
Slow ramp field is missing in the required section of "bigip-fast-templates/http" template schema. As we are not able to deploy the application without slow ramp field.

**Comment by shyawnkarim** [comment]
Thanks for reporting this bug. We are now tracking it internally with ID MYSTIQUE-398.

**Comment by shyawnkarim** [comment]
Are you looking for this field to be flagged as required?

**Comment by frslater** [comment]
Unable to repro on FAST 1.8.0.  App deploys without "slow ramp time" in the parameters, which causes AS3 to apply its default (the same as the FAST default, which is 300).  Response: 200 OK, app deployed normally.
