### ISSUE TITLE
Deployed configurations/templates do not automatically appear on cluster peers

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-appsvcs-templates#55]
### Is your feature request related to a problem? Please describe.
Yes, when I deploy an application via FAST on a cluster member, I do not automatically see the application in FAST on the cluster peer. I have to restart restnoded to view synced information.

### Describe the solution you'd like
FAST on the standby device should periodically refresh or refresh by triggered action so that full visibility and control is fully synced between peers.

### Describe alternatives you've considered
restart sys service restnoded as nec'y

### Additional context
None.

**Comment by delgadillo22** [comment]
Thanks for your feedback. We are tracking this internally as MYSTIQUE-411

**Comment by shyawnkarim** [comment]
This enhancement was included with [Release 1.10](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.10.0).
