### ISSUE TITLE
Import existing AS3 config

### ISSUE THREAD

**Issue by basva923** [F5Networks/f5-appsvcs-templates#56]
We are in the situation where we want to automate the creation of a new application using AS3. We want to use AS3 to have the advantage of simple config backups, backward compatibility, an easy upgrade process, .etc.  But on the other hand we want a GUI to edit the AS3 config if needed.

If another solution already exists, I'm happy to hear it.

### Is your feature request related to a problem? Please describe.
We can not edit existing AS3 config.

### Describe the solution you'd like
The functionality to import & sync the existing AS3 config and edit this config.

**Comment by shyawnkarim** [comment]
We actually have a tutorial on how to create your own FAST templates located [here](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/template-authoring.html).  Please start here and if you run into any problems please feel free to report your issue.
