### ISSUE TITLE
ADFS FAST template - Destination IP not displayed

### ISSUE THREAD

**Issue by raZorTT** [F5Networks/f5-appsvcs-templates#60]
### Environment
 * FAST RPM Version: 1.10.0
 * BIG-IP Version: 14.1

### Summary
When deploying an application using the ADFS FAST template, I'm not given the option to enter the destination IP address unless I enable the Microsoft Alternate Port Client Certificate Authentication option. If you deploy the template the destination IP is set to the default 10.1.1.1

### Steps To Reproduce
- Start new ADFS deployment using ADFS template
- Virtual Server IP is not visible

### Expected Behavior
To be able to enter a destination IP if Microsoft Alternate Port Client Certificate Authentication option is not enabled.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-428.

**Comment by shyawnkarim** [comment]
This bug fix was included with [Release 1.11.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.11.0).
