### ISSUE TITLE
ADFS FAST template - Pool Members IP not displayed

### ISSUE THREAD

**Issue by pbroobi** [F5Networks/f5-appsvcs-templates#62]
### Environment
 * FAST RPM Version: 1.11
 * BIG-IP Version:15.1.3

### Summary
When deploying an application using the ADFS FAST template, I'm not given the option to enter the pool members IP address unless I enable the Microsoft Alternate Port Client Certificate Authentication option. 

### Steps To Reproduce
Start new ADFS deployment using ADFS template
Virtual Server IP is not visible

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by shyawnkarim** [comment]
Closing.

This bug fix was included with [Release 1.12.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.12.0).
