### ISSUE TITLE
Authorization token instead of basic auth.

### ISSUE THREAD

**Issue by DorSA9** [F5Networks/f5-appsvcs-templates#67]
### Is your feature request related to a problem? Please describe.
the most common open-source ipams (phpIpam & netbox) are working with authorization token instead of basic auth, when API access is needed

### Describe the solution you'd like
adding the option of token authorization.

### Describe alternatives you've considered
tried a few open-source IPAMs, none of them work with basic auth.

Thank you very much in advance!

**Comment by delgadillo22** [comment]
Thank you -- we are tracking this internally as MYSTIQUE-442.

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
