### ISSUE TITLE
Unable to submit rendered template 

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-templates#7]
### Environment
 * FAST RPM Version: 1.10
 * BIG-IP Version: 15.1.0.3

### Summary

I'm unable to "submit" the rendered template of a custom mst  (syntax checks out).
```
Failed to submit application:
Error: Failed to get data from /mgmt/shared/fast/applications: 400 Bad Request
{
  "code": 400,
  "message": "HTML Tag-like Content in the Request URL/Body"
}
    at https://192.168.1.201/iapps/f5-appsvcs-templates/bundle.js:77275:23
```

### Steps To Reproduce
List the steps to reproduce the behavior:

Use mst/params from: https://github.com/f5devcentral/f5-fast-core/issues/2

### Expected Behavior
It works

### Actual Behavior
It does not.

**Comment by chen23** [comment]
This looks related to the use of Common/Shared?  When I create separate templates for each tenant it works.

**Comment by zinkem5** [comment]
Looks like this is related to the use of multiple tenants in a single template. 

Currently, FAST only supports 1 tenant and 1 application per template. We are revising the error message to be clearer.

**Comment by mstokes-f5** [comment]
FAST v1.4.0 improved the error messages reported when attempting to use a template that outputs more than one tenant or more than one application. If there is a desire to lift this restriction, please file an enhancement request (or re-open this ticket and restructure it as an enhancement).
