### ISSUE TITLE
Please add the option to select an intermediate certificate for the Exchange FAST template

### ISSUE THREAD

**Issue by jjkendrick** [F5Networks/f5-appsvcs-templates#70]

**Comment by delgadillo22** [comment]
Thank you -- added to backlog as MYSTIQUE-443

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
