### ISSUE TITLE
Fields which are not mandatory while deploying the FAST application still appear in the required section of FAST template schema

### ISSUE THREAD

**Issue by vishwajeetgslab** [F5Networks/f5-appsvcs-templates#72]
### Environment
 * FAST RPM Version:1.11.0
 * BIG-IP Version:15.1.2.1

### Summary
Fields which are not mandatory while deploying the FAST application still appear in the required section of FAST template schema. On BIG-IP FAST UI some fields are not added with asterisk (*) but in the schema these are present under the required section.
![image](https://user-images.githubusercontent.com/61869155/133746409-2f5adcd4-b07f-472c-88c3-16744f3dd68c.png)

### Steps To Reproduce
List the steps to reproduce the behavior:
1. Navigate to iApps  ››  Application Services : Applications LX ››  F5 Application Services Templates >>
2. Open HTTP Application Template
3. Check Endpoint Policies and iRules
4. Check the required section of template schema from debug view at the end

### Expected Behavior
Fields which are not mandatory while deploying the FAST application should be removed from required section of FAST template schema

### Actual Behavior
Fields which are not mandatory while deploying the FAST application still appear in the required section of FAST template schema

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. We are now tracking it internally with ID MYSTIQUE-447.

**Comment by shyawnkarim** [comment]
Closing.

The fix for this was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
