### ISSUE TITLE
app_fqdn wrong dependencies break FQDN in HTTP monitor

### ISSUE THREAD

**Issue by rene-geile** [F5Networks/f5-appsvcs-templates#73]
### Environment
 * FAST RPM Version: 1.11.0-1
 * BIG-IP Version: 15.1.3.1

### Summary
Exchange template: Configuration dialog does not display Exchange Domain name entry field if certain services are not enabled 
This causes the app_fqdn value to be empty. Afterwards HTTP Monitor is created with Host Header "example.mycompany.com".

### Steps To Reproduce
Use FAST template to configure OWA and Autodiscover only:

"Outlook Web App" Enable 
"EWS" Disable
"Microsoft Outlook and OAB" Disable
"Active Sync" Disable
"Autodiscover" Enable
"Pop 3" Disable
"IMAP4" Disable

=> No FQDN field.

### Expected Behavior
Entry field for FQDN should be independent from selected services so its always possible to enter Exchange Domain Name and
HTTP Monitor should be using correct Host Header.

### Actual Behavior

Restrictive dependencies:

"app_fqdn": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255,
      "pattern": "^[A-Za-z][0-9A-Za-z_.-]*$",
      "title": "Exchange Domain Name",
      "description": "Specify the fully qualified domain name you are using for all of the HTTP-based client access services.",
      "propertyOrder": 2,
      "options": {
        "dependencies": {
          "autodiscover": true,
          "single_vip": true,
          "activesync": true,
          "ews": true,
          "outlook": true,
          "outlookRPC": true,
          "owa": true,
          "outlookMAPI": true
        }
      }

Created monitors:
ltm monitor https /rene.testlab/webmail.rene.testlab/exchangeVS_ad_https_monitor {
    adaptive disabled
    adaptive-limit 1000
    adaptive-sampling-timespan 180
    cipherlist DEFAULT
    defaults-from /Common/https
    destination *:*
    interval 10
    ip-dscp 0
    recv "200 OK"
    recv-disable none
    send "GET /autodiscover/healthcheck.htm HTTP/1.1\r\nHost: example.mycompany.com\r\nConnection: Close\r\n\r\n"
    time-until-up 0
    timeout 31
}
ltm monitor https /rene.testlab/webmail.rene.testlab/exchangeVS_owa_https_monitor {
    adaptive disabled
    adaptive-limit 1000
    adaptive-sampling-timespan 180
    cipherlist DEFAULT
    defaults-from /Common/https
    destination *:*
    interval 10
    ip-dscp 0
    recv "200 OK"
    recv-disable none
    send "GET /owa/healthcheck.htm HTTP/1.1\r\nHost: example.mycompany.com\r\nConnection: Close\r\n\r\n"
    time-until-up 0
    timeout 31
}

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. We are now tracking it internally with ID MYSTIQUE-448.

**Comment by shyawnkarim** [comment]
Closing.

The fix for this was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
