### ISSUE TITLE
Exchange Template - Problem in Chrome because of SameSite=None / Secure Flag

### ISSUE THREAD

**Issue by mkretzer** [F5Networks/f5-appsvcs-templates#77]
We are currently using the Exchange FAST template with SSL Offloading.
The issue is that the resulting cookies have SameSite=None and do not have the Secure flag set, therefore Google Chrome blocks them, rendering login impossible.
We can work around this by enabling an iRule on the virtual server.
 
when HTTP_RESPONSE {
    foreach mycookie [HTTP::cookie names] {
    HTTP::cookie secure $mycookie enable
   }
}
 
However this iRule becomes unlinked from the vs when redeploying from the app template.
Could you include this iRule as a template setting?

**Comment by shyawnkarim** [comment]
Thanks for submitting your issue. We are now tracking this enhancement internally with ID MYSTIQUE-455.

**Comment by shyawnkarim** [comment]
Closing.

This enhancement  was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
