### ISSUE TITLE
LDAP template fails to deploy

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-appsvcs-templates#78]
https://github.com/F5Networks/f5-appsvcs-templates/blob/master/templates/bigip-fast-templates/ldap.yaml
BIG-IP v16.1.0 build 0.0.19
f5-appsvcs-templates version 1.12.0, build 1
f5-appsvcs version 3.31.0, build 6

Please consider correcting these 2 issues with the LDAP template:

1. The "FAST- Generated Pool" option incorrectly offers default port "80" for the pool members instead of "389".
2. The "FAST-Generated Pool Monitor" option does not display the required "password" field, which prevents the deployment from succeeding. The resulting error info is as follows: "_/test/test/test_monitor/**passphrase/ciphertext: should NOT be shorter than 2 characters**_"

**Comment by shyawnkarim** [comment]
Thanks for reporting these issues. We are now tracking them internally with ID MYSTIQUE-456.

**Comment by shyawnkarim** [comment]
Closing.

The fix for this was included with [Release 1.13.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.13.0).
