### ISSUE TITLE
fast cli tool only allows packageTemplateSet of a path instead of being file specific

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-templates#79]
When using the fast cli tool to package a .mst template file it only allows to package from a path.

fast packageTemplateSet <templateSetPath>

If there is a great reason why using path has been preferred above being file-specific, then please explain this in the documentation.

Can you add more .mst files along the way to a package as you can with 'zip'? How will this impact existing templates and can this break deployed fast templates?

I would prefer to have more options on how one can package and make it more user-friendly.

features to add are:
- ability to add files to the packaged file, to get a consistent FAST template overview on BIG-IP.
- be file specific instead of only being able to define a path.

### Environment
 * FAST RPM Version: 1.11
 * BIG-IP Version: 16.0.1.1

**Comment by shyawnkarim** [comment]
Closing.

After a review of this request, we have decided to not implement this feature.

**Comment by gwolfis** [comment]
Hi Shyawn,

Then as a bare minimum explain how the packageTemplateSet works and how to use this from a best practice.

Just be aware that using .zip or using packageTemplateSet differs from an outcome perspective, because .zip does allow you to select on file level.

Best regards,


[A picture containing clipart  Description automatically generated]
 Gert Wolfis  | EMEA Cloud Solution Architect
 M +31 657022078






From: Shyawn Karim ***@***.***>
Date: Monday, 20 December 2021 at 21:44
To: F5Networks/f5-appsvcs-templates ***@***.***>
Cc: Gert Wolfis ***@***.***>, Author ***@***.***>
Subject: Re: [F5Networks/f5-appsvcs-templates] fast cli tool only allows packageTemplateSet of a path instead of being file specific (#79)

EXTERNAL MAIL: ***@***.***

Closing.

After a review of this request, we have decided to not implement this feature.
