### ISSUE TITLE
FAST templates do not exist for iApps "Deprecated and replaced with new FAST"

### ISSUE THREAD

**Issue by ryn9** [F5Networks/f5-appsvcs-templates#8]
### Is your feature request related to a problem? Please describe.

The following article calls out that FAST templates are replacing a number of iApps and that a number of the iApps are already deprecated
https://support.f5.com/csp/article/K13422

The column "Deprecated and replaced with new FAST", lists iApps that are deprecated and should be replaced with FAST...
Deprecated and replaced with new FAST
f5.http
f5.microsoft_adfs
f5.microsoft_exchange_2010_2013
f5.microsoft_exchange_2016
f5.microsoft_sharepoint_2016
f5.microsoft_skype_server_2015
f5.smtp
f5.tcp
f5.dns
f5.ldap
f5.microsoft_iis

https://github.com/F5Networks/f5-appsvcs-templates/tree/master/templates/bigip-fast-templates
shows only templates for "http" and "tcp" (There is also an "f5" file - but that is not a template). Many of the aforementioned to not exist.

Additionally loading the latest version of FAST does not show these templates as being available.

### Describe the solution you'd like
I would like to see the other "Deprecated and replaced with new FAST" templates made available

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by delgadillo22** [comment]
Thank you for your question. Our initial focus on FAST templates is around protocol-based use cases and will be followed by additional templates in the list above during the course of this year. Which templates are most important for you moving forward? Thanks, Kevin (FAST Product Manager)

**Comment by ryn9** [comment]
We would like to start testing with f5.microsoft_exchange_2016.
We will also need to understand what customization can be applied after deployment (similar to modifying components after an iApp has been deployed).

**Comment by ApolloDS** [comment]
I also work with F5 customers onsite and they're using iApps and Guided Configuration.
Since there is now a third solution to the whole orchestration/automation topic which is now called FAST, the customers ask me what would be the future of all this?

Some features are in iApps, some in Guided Configuration and now in FAST.

Please F5, tell us what the future would be and what the customers should do now to migrate from one to another, this is more important than release new ways of doing templating...

If there any roadmap or so available which we can give to the customers?

Thanks

**Comment by delgadillo22** [comment]
Hello, I am pleased to announce that, with the release of FAST 1.5, we've delivered the FAST templates needed to replace the deprecated iApp templates per https://support.f5.com/csp/article/K13422.

**Comment by delgadillo22** [comment]
> I also work with F5 customers onsite and they're using iApps and Guided Configuration.
> Since there is now a third solution to the whole orchestration/automation topic which is now called FAST, the customers ask me what would be the future of all this?
> 
> Some features are in iApps, some in Guided Configuration and now in FAST.
> 
> Please F5, tell us what the future would be and what the customers should do now to migrate from one to another, this is more important than release new ways of doing templating...
> 
> If there any roadmap or so available which we can give to the customers?
> 
> Thanks

FAST will replace our legacy iApp templates. The Access Guided Configurations are built on a completely different technology than iApps and will continue to be offered for their specific use cases.
