### ISSUE TITLE
FAST input fields display a different default value in FAST schema however a different default value is displayed on BIG-IP FAST form

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-appsvcs-templates#82]
### Environment
 * FAST RPM Version: 1.13.0
 * BIG-IP Version: 15.1.2.1

### Summary
The following FAST input fields display a different default value in FAST schema however a different default value is displayed on BIG-IP FAST form. Please refer below images for reference.
FAST input fields:
1. Virtual Server Port - Bluegreen Template
2. Virtual Server Port - SMTP Template
3. Fallback persistence - TCP Template

<img width="895" alt="bluegreen vip ui" src="https://user-images.githubusercontent.com/88710971/139804815-b4711d01-2c01-4bba-b1b5-5b7075bdfbc6.png">

<img width="904" alt="issue 2 fast schema" src="https://user-images.githubusercontent.com/88710971/139804822-63f84268-0649-4201-b931-9f0908cd842c.png">

### Steps To Reproduce
1. Go to iApps->Application Services -> Applications Lx -> F5 Application Services Templates 
2. Select any one of the above templates
3. Compare the input field values with the FAST schema
4. To view FAST Schema, Go to bottom of the page and expand Debug view
5. Click on Schema Tab from Debug view

### Expected Behavior
The default values displayed on BIG-IP FAST form & FAST schema should be consistent

### Actual Behavior
The default values for the above input fields displayed on BIG-IP FAST form & FAST schema are different

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-472.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.14.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.14.0).
