### ISSUE TITLE
FAST input fields with field type as boolean and no default property are not assumed to be true on BIG-IP UI

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-appsvcs-templates#84]
### Environment
 * FAST RPM Version: 1.13.0
 * BIG-IP Version: 15.1.2.1

### Summary
The following FAST input fields with field type as boolean and no default property are not assumed to be true on BIG-IP UI
FAST input fields:
1. SNMP-Based External Monitoring - Microsoft Exchange Template
2. TLS Server Chain Certificate Bundle - Microsoft Exchange Template
3. TLS Client - Microsoft Exchange Template
4. RPC-over-HTTP - Microsoft Exchange Template
5. IMAP4 - Microsoft Exchange Template
6. POP3 - Microsoft Exchange Template

<img width="929" alt="issue 4 bigip ui" src="https://user-images.githubusercontent.com/88710971/139806411-427df945-ca16-4b09-acef-06a6d62efa90.png">

<img width="920" alt="issue 3 fast schema" src="https://user-images.githubusercontent.com/88710971/139806412-52775394-484e-4afe-a3f7-33fe6982979b.png">

### Steps To Reproduce
1. Go to iApps->Application Services -> Applications Lx -> F5 Application Services Templates
2. Select any one of the above templates
3. Compare the boolean type field values with the FAST schema
4. To view FAST Schema, Go to bottom of the page and expand Debug view
5. Click on Schema Tab from Debug view

### Expected Behavior
The FAST checkbox fields with type as boolean and that have no default property should be selected by default

### Actual Behavior
The FAST checkbox fields with type as boolean and that have no default property are not selected by default

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-474.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.14.1](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.14.0).
