### ISSUE TITLE
Ability to rename applications within a tenant

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-appsvcs-templates#89]
Is there a way to rename an application within a tenant in a single FAST API call? I believe the proper procedure would be to snapshot the existing app via API, update the application name, delete the existing FAST deployment and then resend the FAST deployment with the updated application name value.

**Comment by delgadillo22** [comment]
Hi, no there isn't a way to rename an application within a tenant with a single FAST API call. Application name is immutable. As you stated, you'll need to delete and redeploy in order to change the application name.

**Comment by grf5** [comment]
Thank you for the clarification.
