### ISSUE TITLE
FAST Templates gone after reboot

### ISSUE THREAD

**Issue by MSlawik** [F5Networks/f5-appsvcs-templates#92]
I installed latest AS3 and then latest FAST and all was working fine. I have created and deleted Apps without issues. 
After a reboot FAST is broken. After clicking the "F5 Application Services Templates" with the green light left to it, it ends up with this:

To deploy an application, start by selecting a template below
Error fetching templates: Failed to get data from /mgmt/shared/fast/templatesets?userAgent=FASTGUI/NA: 404 Not Found
{
  "code": 404,
  "message": "",
  "referer": "https://10.1.2.100/iapps/f5-appsvcs-templates/index.html",
  "errorStack": []
}
 

BIG-IP is running 16.1.2 and error is reproducable. To get it working I need to remove FAST & AS3 again and re-install. I'm using VSCode F5 plugin for all that.
Interesting is also that VSCode does state that FAST is not installed in the error case:
<img width="166" alt="fast issue" src="https://user-images.githubusercontent.com/22789422/152816819-c4155651-a386-4a91-8cb7-f704ded270b2.png">

### Environment
 * FAST RPM Version: 1.15.0
 * BIG-IP Version: 16.1.2

### Summary
Include information about the reproducibility and the severity/impact of the issue.
See above

### Steps To Reproduce
List the steps to reproduce the behavior:
Install AS3
Install FAST
Create a App with any template
reboot BIG-IP
Issue occurs

### Expected Behavior
The templates should be displayed.

### Actual Behavior
To deploy an application, start by selecting a template below

Error fetching templates: Failed to get data from /mgmt/shared/fast/templatesets?userAgent=FASTGUI/NA: 404 Not Found
{
  "code": 404,
  "message": "",
  "referer": "https://10.1.2.100/iapps/f5-appsvcs-templates/index.html",
  "errorStack": []
}

I can be contacted internally via Teams as well.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. It is now being tracked internally with ID MYSTIQUE-550.

**Comment by shyawnkarim** [comment]
Closing.

The fix for this bug was included with [Release 1.16.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.16.0).
