### ISSUE TITLE
Lost WAF policy option on HTTP FAST Template 

### ISSUE THREAD

**Issue by chungyu2** [F5Networks/f5-appsvcs-templates#93]
### Environment
 * FAST RPM Version: 3.34
 * BIG-IP Version: 15.1.2

### Summary

After removing some iapp with waf templates, the FAST HTTP template now no longer has the option to add WAF or pick the security logging profiles.

### Steps To Reproduce

I remove from the Package Management LX - f5-iappslx-waf-app-xxx IAPP packages, and then when I go back to my FAST template, the WAF policy option is gone and I can not choose a security logging profile.

### Expected Behavior

I expected to be able to choose these features

### Actual Behavior

I would like to have these options back in the FAST Template

**Comment by delgadillo22** [comment]
Thank you for your report. Can you point me to this iApps LX extension?

**Comment by chungyu2** [comment]
Hi Kevin

I am currently using the latest template for FAST

F5-appsvcs-templates version 1.15.0 build 1 and the package is f5-appsvcs-templates-1.15.0-1.noarch

I had removed the f5-appslx-waf-app-protection 1.4.0 – again, I am not sure it is because I removed it, but I just don’t have the WAF policy option right now in my HTTP template anymore.

Thanks

Chung

**Comment by delgadillo22** [comment]
Thanks I'm not familiar with the "f5-appslx-waf-app-protection 1.4.0" iLX extension.
Where is that available? Is this a custom extension?

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you would like to revisit this.
