### ISSUE TITLE
AFM policy option in HTTP FAST Template

### ISSUE THREAD

**Issue by chungyu2** [F5Networks/f5-appsvcs-templates#94]
### Is your feature request related to a problem? Please describe.

No, it is a request for a enhancement

### Describe the solution you'd like

I would like to use a pre-existing AFM policy or at least be able to use the shared objects group to make the AFM policy in FAST Template

### Describe alternatives you've considered

When using the FAST HTTP template, I need to add each subnet manually.

**Comment by shyawnkarim** [comment]
Thanks for submitting this enhancement request. We are now tracking this internally with ID MYSTIQUE-558.

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 1.17.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.17.0).
